### ISSUE TITLE
Failed asserting that null is identical to '<KnightOfNi> Ni!'.

### ISSUE THREAD

**Issue by esteemed** [gnugat-examples/mastering-symfony2#1]
Been following through the tutorial (great tutorial btw) but am getting 1 failure that I can't figure out from this section: http://gnugat.github.io/2014/08/22/master-sf2-part-3-services.html#the-factory-service

Error: 
`Failed asserting that null is identical to '<KnightOfNi> Ni!'.`

Occurs on this line of the test:  
`$this->assertSame(self::CONTENT, $foundQuote['content']);`

I've copied the code as is, and am getting this error any idea why?

**Comment by gnugat** [comment]
Hi, I'm sorry you encountered this error. I'll have a look as soon as possible to understand what happened and I'll get back to you :)

**Comment by gnugat** [comment]
@esteemed I can't reproduce the bug on my end, but here's a wild guess: ca you replace in file `src/Fortune/ApplicationBundle/Entity/QuoteGateway.php` line 18 `$line = $content."\n";` by `$line = $content.PHP_EOL;` and run again the test?

If it still fails, can you dump the content of the file `src/Fortune/ApplicationBundle/Tests/Entity/QuoteRepositoryTest.php`?

Cheers,

**Comment by esteemed** [comment]
Thanks for the suggestion I am still getting the same error. `Failed asserting that null is identical to ' Ni!'.`

By dumping the content of the file do you mean: (in testItPersistsTheQuote() function)

`var_dump($foundQuote['content']); die;` ?

It comes back as `NULL` when I run phpunit -c app.

**Comment by esteemed** [comment]
Checking /tmp/fortune_database_test.txt I see the text being written in the file, so that part is working.

In `testItPersistsTheQuote()` this is what I am getting when dumping :
`$quotes = $this->repository->findAll();
        var_dump($quotes); die;`

array(1) {
  'quotes' =>
  array(12) {
    [0] =>
    array(2) {
      'id' =>
      int(0)
      'content' =>
      NULL
    }
    [1] =>
    array(2) {
      'id' =>
      int(1)
      'content' =>
      NULL
    }

**Comment by esteemed** [comment]
Ok did a var_dump on $quotes in findAllI() in QuoteGateway.php and turns out I spotted a TYPO in the Quote entity file! <sigh> Fixed this and the error no longer appears. Thanks for guiding me in the right direction. On to the next section! :)

**Comment by gnugat** [comment]
I'm glad you could fix your problem :) . Thanks for passing by, and if you have any other question don't hesitate to come back
